import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { money, orderDate } from "@/lib/woodoo";
import { trpc } from "@/lib/trpc";
import { calculateCountertopRun, calculateCountertopSlabPlan, edgeCostBreakdownByRunType } from "@shared/countertopLogic";
import { ArrowLeft, Printer, Ruler, TriangleAlert } from "lucide-react";
import { useLocation } from "wouter";

export default function CountertopTakeoffView({ takeoffId }: { takeoffId: number }) {
  const [, setLocation] = useLocation(); const query = trpc.countertops.takeoff.useQuery({ takeoffId });
  if (query.isLoading) return <DashboardLayout><div className="woodoo-card p-10 text-center text-sm text-[#66756b]">Loading countertop takeoff…</div></DashboardLayout>;
  if (!query.data) return <DashboardLayout><div className="woodoo-card p-10 text-center text-sm text-[#66756b]">This countertop takeoff could not be found.</div></DashboardLayout>;
  const { takeoff, runs, totals } = query.data;
  const rates = { materialCentsPerSquareFoot: takeoff.materialCentsPerSquareFoot, nonEasedEdgeCentsPerLinearFoot: takeoff.nonEasedEdgeCentsPerLinearFoot, trimCentsPerLinearFoot: takeoff.trimCentsPerLinearFoot, sinkCutoutCentsEach: takeoff.sinkCutoutCentsEach, vanitySinkCutoutCentsEach: takeoff.vanitySinkCutoutCentsEach };
  const plan = calculateCountertopSlabPlan(runs, { slabLengthInches: takeoff.slabLengthMilliInches / 1000, slabWidthInches: takeoff.slabWidthMilliInches / 1000, planningWastePercent: takeoff.planningWasteBasisPoints / 100 }); const edgeBreakdown = edgeCostBreakdownByRunType(runs, rates);
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><button onClick={() => setLocation("/countertops")} className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.14em] text-[#637268]"><ArrowLeft size={14} />Countertop builder</button><p className="woodoo-kicker">Saved countertop plan</p><h1 className="mt-1 font-serif text-4xl tracking-tight">{takeoff.materialName}</h1><p className="mt-2 text-sm text-[#66756b]">{takeoff.supplier} · {takeoff.collection} · {takeoff.finish} finish</p></div><Button variant="outline" onClick={() => window.print()}><Printer size={15} />Print</Button></div>
    <section className="woodoo-card overflow-hidden"><div className="grid gap-6 border-b border-[#e5e0d4] p-6 md:grid-cols-2"><div><p className="woodoo-kicker">Project record</p><h2 className="mt-2 text-xl font-semibold">{takeoff.customerName}</h2><p className="mt-2 text-sm leading-6 text-[#66756b]">Estimate {takeoff.estimateNumber}<br />Saved {orderDate(takeoff.createdAt)}</p>{takeoff.materialSourceUrl && <a className="mt-3 inline-flex text-sm font-semibold text-[#1a5a3c] underline underline-offset-4" href={takeoff.materialSourceUrl} target="_blank" rel="noreferrer">Open material source</a>}<div className="mt-4 rounded-xl border border-[#e3e8e1] bg-[#f7fbf6] p-3"><p className="woodoo-kicker">Supplier slab reference</p><p className="mt-1 font-mono text-lg font-bold">{money(takeoff.supplierSlabPriceCents)}</p><p className="mt-1 text-[11px] leading-4 text-[#758178]">{takeoff.supplierSlabPriceBasis}</p></div></div><div className="rounded-2xl border border-[#d9ded8] bg-[#f7fbf6] p-4"><div className="flex items-center gap-2 text-[#355747]"><Ruler size={16} /><p className="woodoo-kicker">Locked labor and planning basis</p></div><dl className="mt-3 grid grid-cols-2 gap-y-3 text-sm"><dt className="text-[#758178]">Material / labor</dt><dd className="font-mono font-semibold">{money(rates.materialCentsPerSquareFoot)}/sq ft</dd><dt className="text-[#758178]">Non-eased edge</dt><dd className="font-mono font-semibold">{money(rates.nonEasedEdgeCentsPerLinearFoot)}/lf</dd><dt className="text-[#758178]">Trim allowance</dt><dd className="font-mono font-semibold">{money(rates.trimCentsPerLinearFoot)}/lf</dd><dt className="text-[#758178]">Planning slab</dt><dd className="font-mono font-semibold">{(takeoff.slabLengthMilliInches / 1000).toFixed(0)} × {(takeoff.slabWidthMilliInches / 1000).toFixed(0)} in</dd><dt className="text-[#758178]">Planning waste</dt><dd className="font-mono font-semibold">{(takeoff.planningWasteBasisPoints / 100).toFixed(1)}%</dd><dt className="text-[#758178]">Edge workflow</dt><dd className="font-semibold">{takeoff.edgeMode === "Shared" ? `${takeoff.sharedEdgeProfile ?? "Shared"}` : `Perimeter: ${takeoff.perimeterEdgeProfile} · Island: ${takeoff.islandEdgeProfile}`}</dd></dl></div></div>
      <div className="grid gap-3 border-b border-[#e5e0d4] bg-[#fbfaf5] p-5 sm:grid-cols-5">{[["Planned slabs", plan.slabCount], ["Coverage", `${plan.plannedCoverageSquareFeet.toFixed(1)} sq ft`], ["Allowance", `${plan.leftoverSquareFeet.toFixed(1)} sq ft`], ["Seams", plan.seamCount], ["Review runs", plan.seamReviewCount]].map(([label, value]) => <div key={String(label)}><p className="woodoo-kicker">{label}</p><p className="mt-1 font-mono text-lg font-bold">{value}</p></div>)}</div>
      {plan.seamReviewCount > 0 && <div className="mx-6 mt-5 flex gap-2 rounded-xl border border-[#e7d2ad] bg-[#fff7e8] p-3 text-sm text-[#76501c]"><TriangleAlert size={17} className="shrink-0" />Seam positions are a planning aid only. Confirm layout, vein matching, and final seam placement with the fabricator before release.</div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left"><thead className="bg-[#faf9f4] text-[10px] font-bold uppercase tracking-[.14em] text-[#728076]"><tr><th className="px-6 py-4">Cabinet-top run</th><th className="px-4 py-4">Dimensions / plan</th><th className="px-4 py-4">Edge / trim</th><th className="px-4 py-4">Window / sink</th><th className="px-4 py-4 text-right">Seams</th><th className="px-6 py-4 text-right">Run total</th></tr></thead><tbody className="divide-y divide-[#ece8df]">{runs.map((run, index) => { const line = calculateCountertopRun(run, rates); const runPlan = plan.runPlans[index]; return <tr key={run.id}><td className="px-6 py-4"><p className="text-sm font-semibold">{run.label}</p><p className="mt-1 text-[11px] text-[#758178]">{run.room} · {run.runType}{run.note ? ` · ${run.note}` : ""}</p></td><td className="px-4 py-4 font-mono text-sm">{run.lengthInches.toFixed(2)} × {run.depthInches.toFixed(2)} in<p className="mt-1 text-[11px] text-[#758178]">{line.squareFeet.toFixed(2)} sq ft · {run.seamPreference}</p></td><td className="px-4 py-4 text-sm">{run.edgeProfile}<p className="mt-1 font-mono text-[11px] text-[#758178]">{run.edgeLinearFeet.toFixed(1)} lf edge · {money(line.edgeCents)}</p><p className="font-mono text-[11px] text-[#758178]">{run.trimLinearFeet.toFixed(1)} lf trim · {money(line.trimCents)}</p></td><td className="px-4 py-4 text-xs"><p>Window sill: {run.windowHeightOffFloorInches == null ? "—" : `${run.windowHeightOffFloorInches.toFixed(1)} in AFF`}</p><p className="mt-1">{run.sinkCutoutCount} standard · {run.vanitySinkCutoutCount} vanity</p><p className="mt-1">Integrated: {run.integratedSink ? "Review required" : "No"}</p></td><td className="px-4 py-4 text-right text-xs"><p className={runPlan.needsSeamReview ? "font-semibold text-[#a24a35]" : "text-[#4c6a57]"}>{runPlan.seamCount ? `${runPlan.seamCount} seam` : "No seam"}</p><p className="mt-1 text-[#758178]">{runPlan.seamPositionsInches.length ? runPlan.seamPositionsInches.map(value => `${value.toFixed(0)} in`).join(", ") : ""}</p></td><td className="px-6 py-4 text-right font-mono font-bold">{money(line.totalCents)}</td></tr>; })}</tbody></table></div>
      <div className="flex justify-end border-t border-[#e5e0d4] bg-[#fbfaf5] px-6 py-5"><div className="w-full max-w-sm space-y-2 text-right text-sm"><div className="flex justify-between gap-8"><span className="text-[#758178]">Material / labor · {totals.squareFeet.toFixed(2)} sq ft</span><span className="font-mono font-semibold">{money(totals.materialCents)}</span></div><div className="flex justify-between gap-8"><span className="text-[#758178]">Perimeter edges / trim</span><span className="font-mono font-semibold">{money(edgeBreakdown.Perimeter.edgeCents + edgeBreakdown.Perimeter.trimCents)}</span></div><div className="flex justify-between gap-8"><span className="text-[#758178]">Island edges / trim</span><span className="font-mono font-semibold">{money(edgeBreakdown.Island.edgeCents + edgeBreakdown.Island.trimCents)}</span></div><div className="flex justify-between gap-8"><span className="text-[#758178]">Standard + vanity cutouts</span><span className="font-mono font-semibold">{money(totals.sinkCutoutCents + totals.vanitySinkCutoutCents)}</span></div><div className="flex items-end justify-between gap-8 border-t border-[#e4e0d6] pt-2"><p className="woodoo-kicker">Countertop total</p><p className="font-mono text-2xl font-bold">{money(totals.totalCents)}</p></div></div></div>
    </section></div></DashboardLayout>;
}
