import DashboardLayout from "@/components/DashboardLayout";
import { DeleteOrderDialog } from "@/components/DeleteOrderDialog";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { money, orderDate, type OrderStatus } from "@/lib/woodoo";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList, Copy, Eye, FilePlus2, Pencil, Plus, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";

export default function Home() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const orders = trpc.orders.list.useQuery();
  const duplicate = trpc.orders.duplicate.useMutation({ onSuccess: data => { toast.success("Draft copy created."); utils.orders.list.invalidate(); setLocation(`/orders/${data.order.id}`); }, onError: error => toast.error(error.message) });
  const rows = orders.data ?? [];
  const count = (status: OrderStatus) => rows.filter(row => row.status === status).length;
  const committed = rows.filter(row => row.status !== "Draft").reduce((sum, row) => sum + row.subtotalCents, 0);

  return <DashboardLayout><div className="mx-auto max-w-7xl"><section className="relative overflow-hidden rounded-[28px] border border-[#e5e0d4] bg-[#fffef9] px-7 py-9 shadow-[0_16px_40px_rgba(48,55,39,.06)] lg:px-8"><div className="absolute -right-10 -top-14 h-48 w-48 rounded-full border-[18px] border-[#eee9dc]" /><div className="relative max-w-3xl"><p className="woodoo-kicker">Design Your Price · Cabinet operations</p><h1 className="mt-3 font-serif text-4xl leading-[1.05] tracking-tight text-[#17291f] sm:text-5xl">Cabinet orders, <em className="font-normal text-[#5d7568]">with certainty.</em></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#607067]">Build, verify, and prepare Woodoo orders from the imported MSRP catalog—without hand-entering a single unit price.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setLocation("/orders/new")} className="gap-2 bg-[#0d3b26] hover:bg-[#12462d]"><FilePlus2 size={16} />Create order</Button><Button variant="outline" onClick={() => setLocation("/catalog")} className="gap-2 border-[#d8d4ca] bg-white"><ClipboardList size={16} />Browse catalog</Button></div></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "All orders", value: rows.length, detail: "Active records", icon: ClipboardList }, { label: "Draft", value: count("Draft"), detail: "In progress", icon: Pencil }, { label: "Verified", value: count("Verified"), detail: "Ready for release", icon: ShieldCheck }, { label: "Committed value", value: money(committed), detail: "Verified + submitted", icon: CheckCircle2 }].map(card => { const Icon = card.icon; return <div key={card.label} className="woodoo-card p-5"><div className="flex items-start justify-between"><p className="woodoo-kicker">{card.label}</p><span className="grid h-8 w-8 place-items-center rounded-full bg-[#eff0e6] text-[#49614f]"><Icon size={15} /></span></div><p className="mt-5 font-mono text-2xl font-bold">{card.value}</p><p className="mt-1 text-xs text-[#758178]">{card.detail}</p></div>; })}</section>
    <section className="woodoo-card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-[#e5e0d4] px-6 py-5"><div><p className="woodoo-kicker">Order ledger</p><h2 className="mt-1 text-xl font-semibold">Current cabinet orders</h2></div><Button variant="ghost" onClick={() => setLocation("/orders/new")} className="gap-2 text-[#0d3b26]">New order <Plus size={16} /></Button></div>{orders.isLoading ? <div className="p-10 text-center text-sm text-[#66756b]">Loading orders…</div> : rows.length === 0 ? <div className="p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eff0e6] text-[#48604e]"><ClipboardList size={21} /></div><h3 className="mt-4 text-lg font-semibold">Your order ledger is ready.</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#66756b]">Start an order to pull cabinet configurations directly from the Woodoo MSRP catalog.</p><Button onClick={() => setLocation("/orders/new")} className="mt-5 bg-[#0d3b26] hover:bg-[#12462d]">Build the first order</Button></div> : <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="bg-[#faf9f4] text-[10px] font-bold uppercase tracking-[.14em] text-[#728076]"><tr><th className="px-6 py-4">Estimate / customer</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Items</th><th className="px-4 py-4">Value</th><th className="px-4 py-4">Updated</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#ece8df]">{rows.map(order => <tr key={order.id} className="hover:bg-[#fcfbf7]"><td className="px-6 py-4"><p className="font-mono text-xs font-bold text-[#0d3b26]">{order.estimateNumber}</p><p className="mt-1 text-sm font-medium">{order.customerName}</p></td><td className="px-4 py-4"><StatusPill status={order.status} /></td><td className="px-4 py-4 text-sm text-[#627168]">{order.itemCount}</td><td className="px-4 py-4 font-mono text-sm font-bold">{money(order.subtotalCents)}</td><td className="px-4 py-4 text-sm text-[#627168]">{orderDate(order.updatedAt)}</td><td className="px-6 py-4"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={() => setLocation(`/orders/${order.id}/view`)} className="gap-1.5"><Eye size={14} />View</Button><Button size="sm" variant="outline" onClick={() => setLocation(`/orders/${order.id}`)} className="gap-1.5"><Pencil size={14} />Edit</Button><Button size="sm" variant="ghost" onClick={() => duplicate.mutate({ orderId: order.id })} disabled={duplicate.isPending} className="gap-1.5 text-[#48604e]"><Copy size={14} />Duplicate</Button><DeleteOrderDialog orderId={order.id} estimateNumber={order.estimateNumber} /></div></td></tr>)}</tbody></table></div>}</section></div></DashboardLayout>;
}
