import { trpc } from "@/lib/trpc";
import { DOOR_STYLES, FINISH_COLORS, money, roomFromCategory, type CatalogItem } from "@/lib/woodoo";
import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "./ui/button";

export function CatalogBrowser({ onAdd, addLabel = "Add", limit = 60 }: { onAdd?: (item: CatalogItem) => void; addLabel?: string; limit?: number }) {
  const [query, setQuery] = useState("");
  const [room, setRoom] = useState<"Kitchen" | "Bath" | "">("");
  const [doorStyle, setDoorStyle] = useState<(typeof DOOR_STYLES)[number]>("Shaker");
  const [finishColor, setFinishColor] = useState<(typeof FINISH_COLORS)[number]>("White");
  const filters = useMemo(() => ({ query: query || undefined, room: room || undefined, doorStyle, finishColor, limit }), [query, room, doorStyle, finishColor, limit]);
  const catalog = trpc.catalog.list.useQuery(filters);
  return <section className="woodoo-card overflow-hidden"><div className="border-b border-[#e4e0d6] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="woodoo-kicker flex items-center gap-2"><SlidersHorizontal size={13} />Woodoo MSRP catalog</p><h2 className="mt-1 text-xl font-semibold">Select a source-priced cabinet</h2><p className="mt-1 text-sm text-[#66756b]">Every unit price is resolved from the imported Woodoo MSRP table.</p></div><p className="text-xs text-[#66756b]">{catalog.data?.length ?? 0} configurations shown</p></div><div className="mt-5 grid gap-3 md:grid-cols-[1.6fr_.7fr_.8fr_.8fr]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-[#77847a]" size={16} /><input value={query} onChange={event => setQuery(event.target.value)} className="woodoo-input pl-10" placeholder="Code or description" /></label><select value={room} onChange={event => setRoom(event.target.value as "Kitchen" | "Bath" | "")} className="woodoo-input"><option value="">All rooms</option><option>Kitchen</option><option>Bath</option></select><select value={doorStyle} onChange={event => setDoorStyle(event.target.value as (typeof DOOR_STYLES)[number])} className="woodoo-input">{DOOR_STYLES.map(value => <option key={value}>{value}</option>)}</select><select value={finishColor} onChange={event => setFinishColor(event.target.value as (typeof FINISH_COLORS)[number])} className="woodoo-input">{FINISH_COLORS.map(value => <option key={value}>{value}</option>)}</select></div></div><div className="divide-y divide-[#e8e4da]">{catalog.isLoading && <div className="p-8 text-center text-sm text-[#66756b]">Loading Woodoo MSRP configurations…</div>}{catalog.isError && <div className="p-8 text-center text-sm text-red-700">The pricing catalog could not be loaded.</div>}{catalog.data?.map(item => <div key={item.priceId} className="flex flex-col gap-3 p-5 hover:bg-[#fcfbf7] sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="font-mono text-xs font-bold text-[#0d3b26]">{item.productCode}</span><span className="text-[10px] font-bold uppercase tracking-[.14em] text-[#79847c]">{roomFromCategory(item.category)}</span><span className="text-[10px] font-bold uppercase tracking-[.14em] text-[#79847c]">{item.doorStyle} · {item.finishColor}</span></div><p className="mt-1 text-sm font-medium leading-5">{item.description}</p><p className="mt-1 text-[11px] text-[#758178]">Woodoo MSRP source: {item.sourceLabel}</p></div><div className="flex shrink-0 items-center justify-between gap-4"><span className="font-mono text-base font-bold">{money(item.unitPriceCents)}</span>{onAdd && <Button size="sm" variant="outline" onClick={() => onAdd(item)}>{addLabel}</Button>}</div></div>)}{catalog.data?.length === 0 && !catalog.isLoading && <div className="p-10 text-center text-sm text-[#66756b]">No Woodoo configurations match these filters.</div>}</div></section>;
}
